### ISSUE TITLE
More Guidelines?

### ISSUE THREAD

**Issue by kevinxxq** [rotemtam/ent-grpc-example#1]
Hi Rotem,
Thank you for your great example(It is not like other demo just a file with func main()) and a detail blog.

As I mentioned in my question in project page of ent, I used to working on gRPC via .Net which has different handling styles. 
I may miss some important chapters. I have more confusions:
1. I can see a line of each file as:
// Code generated by entc, DO NOT EDIT.
This is impossible to release a service with different kinds of function such as DeleteByListId() QueryAllWithComplicatePredictate()... How do you handle that?
2.If the service is for gRPC clients of other platform, we need add option XXX_package , is there a template to do that?

Thank you.

**Comment by rotemtam** [comment]
Hi @kevinxxq ,

Thanks for reaching out. 

> This is impossible to release a service with different kinds of function such as DeleteByListId() QueryAllWithComplicatePredictate()... How do you handle that?

You are correct that `entproto` + `protoc-gen-entgrpc` does not support the creation of custom methods. It may be possible in the future, but what I would currently do is simply generate a second service with the custom methods and mount it on the same server. 

For instance, in this example repo, add a new file `ent/proto/entpb/custom.proto` , where you would define extra methods, for example:

```protobuf
syntax = "proto3";

package entpb;

import "google/protobuf/empty.proto";

option go_package = "github.com/rotemtam/ent-grpc-example/ent/proto/entpb";

message DeleteByListIdRequest {
  // fields
}

service CustomService {
  rpc DeleteByListId ( DeleteByListIdRequest ) returns ( google.protobuf.Empty );
}
```

Then add to `ent/proto/entpb/generate.go` another line to generate pb and grpc structs for  your new service: 
```go
//go:generate protoc -I=.. --go_out=.. --go-grpc_out=.. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative entpb/custom.proto
```

Then, implement your service, in `custom.go`:
```golang

type CustomService struct {
	UnimplementedCustomServiceServer
}

func (c *CustomService) DeleteByListId(ctx context.Context, request *DeleteByListIdRequest) (*emptypb.Empty, error) {
  // your code..
}
```

and in the main code for the server register an instance of this service, something like:
```golang
// Register the User service with the server.
entpb.RegisterUserServiceServer(server, svc)
// Register the Custom service with the server.
entpb.RegisterCustomServiceServer(server, &CustomService{})
```

Re 2:
> 2.If the service is for gRPC clients of other platform, we need add option XXX_package , is there a template to do that?
There isn't a way to this currently but should be pretty simple to do in `entproto`, I will happily accept a PR to do that. If you're interested in contributing that please join our slack channel (link on the top of entgo.io) and ping me!

Have a great weekend
R

**Comment by kevinxxq** [comment]
Thank you.
Great, it is a good guideline to handle custom methods, I thought it for days but no solution. That is micro service and smart way. 

For second one, understand, I will try to understand how to handle it, but for nowdays, too early for a newbie in golang and ent...

Thank you and a good weekend.
